apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: projectmanagement
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: ujjwalraghuvanshi1212/project-service:v1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: SPRING_PROFILES_ACTIVE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: SERVER_PORT
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: project-service-secret
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: project-service-secret
                  key: SPRING_DATASOURCE_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: SPRING_DATASOURCE_URL
            - name: LOGGING_LEVEL_ROOT
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: LOGGING_LEVEL_ROOT
            - name: LOGGING_LEVEL_COM_PROJECTMANAGEMENT
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: LOGGING_LEVEL_COM_PROJECTMANAGEMENT
            - name: HIKARI_MIN_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: HIKARI_MIN_POOL_SIZE
            - name: HIKARI_MAX_POOL_SIZE
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: HIKARI_MAX_POOL_SIZE
            - name: HIKARI_IDLE_TIMEOUT
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: HIKARI_IDLE_TIMEOUT
            - name: HIKARI_MAX_LIFETIME
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: HIKARI_MAX_LIFETIME
            - name: SHOW_SQL
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: SHOW_SQL
            - name: HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: project-service-config
                  key: HIBERNATE_DDL_AUTO
          readinessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: projectmanagement
spec:
  selector:
    app: project-service
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer